panel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

##profile
Route::resource('profile', 'ProfileController');
Route::post('profile-photo-update', 'ProfileController@updatePhoto');



##ALl Ads
Route::get('/ads/published/{id}', 'AdController@published');
Route::get('/ads/unpublished/{id}', 'AdController@unpublished');
Route::get('/ads/delete/{id}', 'AdController@delete');
Route::get('/ads/category/{categoryId}', 'AdController@categorywiseAds');
Route::resource('ads', 'AdController');
Route::get('removed-ad', 'AdController@removedAd');



##location
Route::get('/divisions', 'DivisionController@index')->name('divisions');
Route::resource('division-areas', 'DivisionAreaController');
Route::get('/division-area/{divisionId}','DivisionAreaController@divisionArea' );
Route::get('/division-area/delete/{divisionId}','DivisionAreaController@divisionAreaDelete' );
Route::get('/cities', 'CityController@index')->name('city');
Route::get('city-area/{cityId}', 'CityAreaController@cityArea');
Route::resource('city-areas', 'CityAreaController');

Route::resource('location', 'LocationController');

##category
Route::get('/category-type/{type}', 'CategoryController@categoryType');
Route::resource('category', 'CategoryController');
Route::get('/category/delete/{categoryId}', 'CategoryController@destroy');
Route::get('/category/down/{categoryId}', 'CategoryController@downCategory');
Route::get('/category/up/{categoryId}', 'CategoryController@upCategory');
Route::get('/subcategory/{categoryId}', 'CategoryController@subcategory');


##Brand
Route::get('brand/delete/{brandId}', 'BrandController@destroy');
Route::get('brand/{categoryId}', 'BrandController@categoryWiseBrand');
Route::resource('brand', 'BrandController');


##ItemType
Route::get('item-type/delete/{itemId}', 'ItemTypeController@destroy');
Route::get('item-type/{categoryId}', 'ItemTypeController@categoryWiseItem');
Route::resource('item-type', 'ItemTypeController');

##Feature
Route::get('feature/delete/{featureId}', 'FeatureController@destroy');
Route::get('feature/{categoryId}', 'FeatureController@categoryWisefeature');
Route::resource('feature', 'FeatureController');

panel/resources/views/layouts/_sidebar.blade.php
 
<section class="sidebar">



  <ul class="sidebar-menu" data-widget="tree">
    <li class="header">MAIN NAVIGATION</li>
    <li class="active">
      <a href="{{url('/home')}}">
        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
      </a>
      
    </li>
    <li class="treeview @if(isset($activeMenu)) {{$activeMenu}} @endif">
      <a href="#">
        <i class="fa fa-fw fa-asterisk"></i> <span>Settings</span>
        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
      </a>
      <ul class="treeview-menu" style="@if(isset($activeMenu)) display: block; @endif" >
        <li><a href="{{url('/divisions')}}"><i class="fa fa-circle-o"></i> Division</a></li>
        <li><a href="{{url('/division-areas')}}"><i class="fa fa-circle-o"></i> Division Area</a></li>
           <li><a href="{{route('location.index')}}"><i class="fa fa-circle-o"></i> Location</a></li>
           <li><a href="{{url('/cities')}}"><i class="fa fa-circle-o"></i> City</a></li>
        <li><a href="{{url('/city-areas')}}"><i class="fa fa-circle-o"></i> City Area</a></li>

         <li><a href="{{Route('category.index')}}"><i class="fa fa-circle-o"></i> Category</a></li>
         <li><a href="{{Route('brand.index')}}"><i class="fa fa-circle-o"></i> Brand</a></li>
         <li><a href="{{Route('item-type.index')}}"><i class="fa fa-circle-o"></i> Item Type</a></li>
          <li><a href="{{Route('feature.index')}}"><i class="fa fa-circle-o"></i> Feature </a></li>
       
        <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
      </ul>
    </li>
   

  
    <li class="treeview">
      <a href="#">
        <i class="fa fa-folder"></i> <span>Examples</span>
        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
        <li><a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
        <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
        <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
        <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
        <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
        <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
        <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
        <li><a href="pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
      </ul>
    </li>

    <li class=" @if(isset($active)) {{$active}} @endif"><a href="{{route('ads.index')}}"><i class="fa fa-book"></i> <span>All Ads</span></a></li>
    <li class=" @if(isset($removedAd)) {{$removedAd}} @endif"><a href="{{url('/removed-ad')}}"><i class="fa fa-book"></i> <span>Removed Ads</span></a></li>
    <li class="header">LABELS</li>
    <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
    <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
    <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
  </ul>
</section>

panel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>amar dokan</title>

  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <link rel="stylesheet" href="{{asset('assets/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">

  <link rel="stylesheet" href="{{asset('assets/bower_components/font-awesome/css/font-awesome.min.css')}}">

  <link rel="stylesheet" href="{{asset('assets/bower_components/Ionicons/css/ionicons.min.css')}}">
  <link rel="stylesheet" href="{{asset('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">

  <link rel="stylesheet" href="{{asset('assets/bower_components/jvectormap/jquery-jvectormap.css')}}">

  <link rel="stylesheet" href="{{asset('assets/dist/css/AdminLTE.min.css')}}">

  <link rel="stylesheet" href="{{asset('assets/dist/css/skins/_all-skins.min.css')}}">


  <link rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <a href="{{url('/home')}}" class="logo">
       <span class="logo-mini"><b>Admin</span>
         <span class="logo-lg"><b>Admin</b></span>
       </a>
       <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
           <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
               <ul class="menu">
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('assets/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('assets/dist/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      AdminLTE Design Team
                      <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('assets/dist/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Developers
                      <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('assets/dist/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Sales Department
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="{{asset('assets/dist/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Reviewers
                      <small><i class="fa fa-clock-o"></i> 2 days</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                    page and may cause design problems
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> 5 new members joined
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> You changed your username
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>

        

        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            @if(!empty(Auth::user()->photo))
            <img src="{{asset('assets/user-photo/'.Auth::user()->photo)}}" alt="" class="user-image" alt="User Image" />
            @else
            <img src="{{asset('assets/user-photo/default.png')}}" alt="" class="user-image" alt="User Image" />
            @endif
            <span class="hidden-xs">{{Auth::user()->name}}</span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault();
              document.getElementById('logout-form').submit();">Sign out</a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </li>
            <li>
             <a href="{{route('profile.index')}}" class="btn btn-default btn-flat">Profile</a>
           </li>
         </ul>
       </li>
       <li>
        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
      </li>
    </ul>
  </div>
</nav>
</header>

<aside class="main-sidebar">
  @include('layouts._sidebar')
</aside>

@yield('content')


<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 007
  </div>
  <strong>Copyright &copy; 0009-{{date('Y')}} <a href="javascript:void(0)">Fungisoft</a>.</strong> All rights
  reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane" id="control-sidebar-home-tab"><h2>1</h2></div>
    <div class="tab-pane" id="control-sidebar-settings-tab">2</div>
  </div>
</aside>
<!-- /.control-sidebar -->

  <!-- Add the sidebar's background. This div must be placed
   immediately after the control sidebar -->
   <div class="control-sidebar-bg"></div>

   <input type="hidden" name="" id="siteUrl" value="{{\Request::url()}}" />

   <!-- jQuery 3 -->
   <script src="{{asset('assets/bower_components/jquery/dist/jquery.min.js')}}"></script>
   <!-- Bootstrap 3.3.7 -->
   <script src="{{asset('assets/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
   <!-- FastClick -->
   <script src="{{asset('assets/bower_components/fastclick/lib/fastclick.js')}}"></script>

   <script src="{{asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
   <script src="{{asset('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
   <!-- AdminLTE App -->
   <script src="{{asset('assets/dist/js/adminlte.min.js')}}"></script>
   <!-- Sparkline -->
   <script src="{{asset('assets/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script>
   <!-- jvectormap  -->
   <script src="{{asset('assets/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
   <script src="{{asset('assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
   <!-- SlimScroll -->
   <script src="{{asset('assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
   <!-- ChartJS -->
   <script src="{{asset('assets/bower_components/chart.js/Chart.js')}}"></script>
   <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
   <script src="{{asset('assets/dist/js/pages/dashboard2.js')}}"></script>
   <!-- AdminLTE for demo purposes -->
   <script src="{{asset('assets/dist/js/demo.js')}}"></script>

   @stack('bottom-script')
 </body>
 </html>