panel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

##profile
Route::resource('profile', 'ProfileController');
Route::post('profile-photo-update', 'ProfileController@updatePhoto');



##ALl Ads
Route::get('/ads/published/{id}', 'AdController@published');
Route::get('/ads/unpublished/{id}', 'AdController@unpublished');
Route::get('/ads/delete/{id}', 'AdController@delete');
Route::get('/ads/category/{categoryId}', 'AdController@categorywiseAds');
Route::resource('ads', 'AdController');
Route::get('removed-ad', 'AdController@removedAd');



##location
Route::get('/divisions', 'DivisionController@index')->name('divisions');
Route::resource('division-areas', 'DivisionAreaController');
Route::get('/division-area/{divisionId}','DivisionAreaController@divisionArea' );
Route::get('/division-area/delete/{divisionId}','DivisionAreaController@divisionAreaDelete' );
Route::get('/cities', 'CityController@index')->name('city');
Route::get('city-area/{cityId}', 'CityAreaController@cityArea');
Route::resource('city-areas', 'CityAreaController');

Route::resource('location', 'LocationController');

##category
Route::get('/category-type/{type}', 'CategoryController@categoryType');
Route::resource('category', 'CategoryController');
Route::get('/category/delete/{categoryId}', 'CategoryController@destroy');
Route::get('/category/down/{categoryId}', 'CategoryController@downCategory');
Route::get('/category/up/{categoryId}', 'CategoryController@upCategory');
Route::get('/subcategory/{categoryId}', 'CategoryController@subcategory');


##Brand
Route::get('brand/delete/{brandId}', 'BrandController@destroy');
Route::get('brand/{categoryId}', 'BrandController@categoryWiseBrand');
Route::resource('brand', 'BrandController');


##ItemType
Route::get('item-type/delete/{itemId}', 'ItemTypeController@destroy');
Route::get('item-type/{categoryId}', 'ItemTypeController@categoryWiseItem');
Route::resource('item-type', 'ItemTypeController');

##Feature
Route::get('feature/delete/{featureId}', 'FeatureController@destroy');
Route::get('feature/{categoryId}', 'FeatureController@categoryWisefeature');
Route::resource('feature', 'FeatureController');

panel/app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    //
}

panel/app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\City;

class CityController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::where('status', 1)->orderBy('order_id', 'ASC')->get();
        $data['cities'] = $cities;
         $data['activeMenu'] = 'menu-open';
        // dd($data);
        return view('city.city', $data);
    }
}

panel/resources/views/city/area.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1> City Area</h1>
    <ol class="breadcrumb">
      <li><a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">City area</li>
    </ol>
  </section>

  <section class="content-header" >
   @if(Session::has('info_message'))
   <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Warning! </strong> {{ Session::get('info_message') }}.
  </div>
  @endif

  @if(Session::has('success_message'))

  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Success! </strong> {{ Session::get('success_message') }}.
  </div>
  @endif
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">City Area List</h3>

          <hr>
        </div>

        <div class="box-body table-responsive padding">
          <table id="divisionAreaTable" class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>SL</th>
                <th>Name</th>

                <th>Status</th>
                <th>City</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              @if(!empty($areas) && (count($areas)>0))
              @foreach($areas as $key => $area)
              <tr>
                <td>{{$key+1}}</td>
                <td>{{$area->name}}</td>

                <td>
                  @if($area->status == 1)
                  <span class="label label-success">Approved</span>
                  @else
                  <span class="label label-warning">Pending</span>
                  @endif
                </td>
                <td>
                  <a href="{{url('/city-area/'.$area->cityId)}}"> {{$area->cityName}}</a> 
                </td>
                <td> <a href="{{route('city-areas.edit', $area->id)}}" class="btn btn-xs btn-info">edit</a> 
                  <a href="#" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-xs btn-danger">delete</a>
                </td>
              </tr>
              @endforeach
              @endif
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="box">
        <div class="box-body table-responsive padding">
          @if(!isset($editAreaInfo))
          <h3 class="box-title">Add City Area </h3>
          <hr>
          <form action="{{route('city-areas.store')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
              <label for="area">Area address:</label>
              <input type="text" class="form-control" id="area" name="area" value="{{old('area')}}">
            </div>
            <div class="form-group">
              <label>City: </label>
              <select class="form-control" name="city">

                <option value="">--select one--</option>
                @if(!empty($cities))
                @foreach($cities as $city)
                <option value="{{$city->id}}"  {{ old('city') == $city->id ? 'selected' : '' }}>{{$city->name}}</option>
                @endforeach
                @endif
              </select>
            </div>

            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          @endif


          @if(isset($editAreaInfo))
          <h3 class="box-title">Update City Area </h3>
          <hr>
          <form action="{{route('city-areas.update', $editAreaInfo->id)}}" method="post">
            <input type="hidden" name="_method" value="PATCH">
            {{csrf_field()}}
            <div class="form-group">
              <label for="area">Area address:</label>
              <input type="text" class="form-control" id="area" name="area" value="{{$editAreaInfo->name}}">
            </div>
            <div class="form-group">
              <label>City: </label>
              <select class="form-control" name="city">

                <option value="">--select one--</option>
                @if(!empty($cities))
                @foreach($cities as $city)
                <option value="{{$city->id}}"  {{ $editAreaInfo->city_id == $city->id ? 'selected' : '' }}>{{$city->name}}</option>
                @endforeach
                @endif
              </select>
            </div>
            <div class="form-group">
              <label>Status: </label>
              <select class="form-control" name="status">
                <option value="1" {{ $editAreaInfo->status == 1 ? 'selected' : '' }}>Active</option>
                <option value="0" {{ $editAreaInfo->status == 0 ? 'selected' : '' }}>Inactive</option>
              </select>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          @endif
        </div>
      </div>
    </div>


  </div>
</section>
</div>

@push('bottom-script')
<script>
  $(function () {
    $('#divisionAreaTable').DataTable()

    // $('#divisionAreaTable').DataTable({
    //   'paging'      : true,
    //   'lengthChange': false,
    //   'searching'   : false,
    //   'ordering'    : true,
    //   'info'        : true,
    //   'autoWidth'   : false
    // })
  })
</script>
@endpush
@endsection

panel/resources/views/city/city-area.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>{{$cityInfo->name}} City Area</h1>
    <ol class="breadcrumb">
      <li><a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">{{$cityInfo->name}} City area</li>
    </ol>
  </section>

  <section class="content-header" >
   @if(Session::has('info_message'))
   <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Warning! </strong> {{ Session::get('info_message') }}.
  </div>
  @endif

  @if(Session::has('success_message'))

  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Success! </strong> {{ Session::get('success_message') }}.
  </div>
  @endif
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"><span>{{$cityInfo->name}}</span> City Area List</h3>

          <hr>
        </div>

        <div class="box-body table-responsive padding">
          <table id="divisionAreaTable" class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>SL</th>
                <th>Name</th>

                <th>Status</th>
            
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              @if(!empty($areas) && (count($areas)>0))
              @foreach($areas as $key => $area)
              <tr>
                <td>{{$key+1}}</td>
                <td>{{$area->name}}</td>

                <td>
                  @if($area->status == 1)
                  <span class="label label-success">Approved</span>
                  @else
                  <span class="label label-warning">Pending</span>
                  @endif
                </td>
             
                <td> <a href="#" class="btn btn-xs btn-info">edit</a> 
                  <a href="#" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-xs btn-danger">delete</a>
                </td>
              </tr>
              @endforeach
              @endif
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Add {{$cityInfo->name}} City Area </h3>

          <hr>
        </div>

        <div class="box-body table-responsive padding">
          <form action="{{route('city-areas.store')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
              <label for="area">Area address:</label>
              <input type="text" class="form-control" id="area" name="area" value="{{old('area')}}">
            </div>
            <div class="form-group">
           <input type="hidden" name="city" value="{{$cityInfo->id}}" />
            </div>

            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </div>
      </div>
    </div>


  </div>
</section>
</div>

@push('bottom-script')
<script>
  $(function () {
    $('#divisionAreaTable').DataTable()

    // $('#divisionAreaTable').DataTable({
    //   'paging'      : true,
    //   'lengthChange': false,
    //   'searching'   : false,
    //   'ordering'    : true,
    //   'info'        : true,
    //   'autoWidth'   : false
    // })
  })
</script>
@endpush
@endsection

panel/resources/views/city/city.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        City
        <small>Version 2.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">city</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">City List</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </div>

    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
            <tr>
              <th>SL</th>
              <th>Name</th>
<th>Status</th>
              <th>Detail</th>
              <th>Action</th>
          </tr>
      </thead>
      <tbody>
        @if(!empty($cities) && (count($cities)>0))
        @foreach($cities as $key => $city)
        <tr>
          <td>{{$key+1}}</td>
          <td><a href="{{url('/city-area/'.$city->id)}}">{{$city->name}}</a> </td>

          <td>
            @if($city->status == 1)
            <span class="label label-success">Approved</span>
            @else
            <span class="label label-warning">Pending</span>
            @endif
        </td>
          <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
          <td> <a href="#" class="btn btn-xs btn-info">edit</a> </td>
      </tr>
      @endforeach
      @endif
  </tbody>
</table>
</div>

</div>

</div>
</div>
</section>
</div>
@endsection