panel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

##profile
Route::resource('profile', 'ProfileController');
Route::post('profile-photo-update', 'ProfileController@updatePhoto');



##ALl Ads
Route::get('/ads/published/{id}', 'AdController@published');
Route::get('/ads/unpublished/{id}', 'AdController@unpublished');
Route::get('/ads/delete/{id}', 'AdController@delete');
Route::get('/ads/category/{categoryId}', 'AdController@categorywiseAds');
Route::resource('ads', 'AdController');
Route::get('removed-ad', 'AdController@removedAd');



##location
Route::get('/divisions', 'DivisionController@index')->name('divisions');
Route::resource('division-areas', 'DivisionAreaController');
Route::get('/division-area/{divisionId}','DivisionAreaController@divisionArea' );
Route::get('/division-area/delete/{divisionId}','DivisionAreaController@divisionAreaDelete' );
Route::get('/cities', 'CityController@index')->name('city');
Route::get('city-area/{cityId}', 'CityAreaController@cityArea');
Route::resource('city-areas', 'CityAreaController');

Route::resource('location', 'LocationController');

##category
Route::get('/category-type/{type}', 'CategoryController@categoryType');
Route::resource('category', 'CategoryController');
Route::get('/category/delete/{categoryId}', 'CategoryController@destroy');
Route::get('/category/down/{categoryId}', 'CategoryController@downCategory');
Route::get('/category/up/{categoryId}', 'CategoryController@upCategory');
Route::get('/subcategory/{categoryId}', 'CategoryController@subcategory');


##Brand
Route::get('brand/delete/{brandId}', 'BrandController@destroy');
Route::get('brand/{categoryId}', 'BrandController@categoryWiseBrand');
Route::resource('brand', 'BrandController');


##ItemType
Route::get('item-type/delete/{itemId}', 'ItemTypeController@destroy');
Route::get('item-type/{categoryId}', 'ItemTypeController@categoryWiseItem');
Route::resource('item-type', 'ItemTypeController');

##Feature
Route::get('feature/delete/{featureId}', 'FeatureController@destroy');
Route::get('feature/{categoryId}', 'FeatureController@categoryWisefeature');
Route::resource('feature', 'FeatureController');

panel/app/Http/Controllers/ItemTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Session;
use Auth;
use Redirect;
use App\Category;
use App\ItemType;

class ItemTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['categories'] = Category::where('parent','!=', 0)->where('status', 1)->get();
        $data['itemTypes'] = ItemType::where('status', '!=' ,5)->get();
        $data['activeMenu'] = 'menu-open';
        return view('item-type.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        // dd($request->category);
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'category' => 'required',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
            ->withErrors($validator)
            ->withInput();
        } else {
            $item = new ItemType;
            $item->title = $request->title;
            $item->category_id = $request->category;
            $item->status = 1;
            $item->order_id = ItemType::where('category_id', $request->category)->max('order_id') + 1;
            $item->created_at = date('Y-m-d');
            $item->updated_at = null;
// dd($item);
            $item->save();
            Session::flash('success_message', 'A item has been Inserted successfully');
            return Redirect::back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $itemInfo = ItemType::where('id', $id)->where('status', '!=', 5)->first();
        if(!empty($itemInfo)){
           $data['categories'] = Category::where('parent','!=', 0)->where('status', 1)->get();
           $data['itemInfo'] = $itemInfo;
           $data['activeMenu'] = 'menu-open';
           return view('item-type.edit', $data);
       }
       else{
        return abort('404');
    }
    
}

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
     $validator = Validator::make($request->all(), [
        'title' => 'required',
        'category' => 'required',
    ]);

     if ($validator->fails()) {
        return Redirect::back()
        ->withErrors($validator)
        ->withInput();
    } else {
        $item = ItemType::find($id);
        $item->title = $request->title;
        $item->category_id = $request->category;
        $item->status = $request->status;
        $item->updated_at = date('Y-m-d');
// dd($item);
        $item->update();
        Session::flash('success_message', 'A item has been Updated successfully');
        return Redirect::to('item-type');
    }
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
     $itemInfo = ItemType::where('id', $id)->first();

     if(!empty($itemInfo)){
        
        $itemInfo->status = 5;
        $itemInfo->updated_at = date('Y-m-d');
        $itemInfo->update();
        Session::flash('success_message', 'A item has been Remove successfully');
        return Redirect::back();

    }
    else{
        return abort('404');
    }
}

public function categoryWiseBrand($categoryId){
    $categoryInfo = Category::where('id', $categoryId)->where('status', 1)->first();

    if(!empty($categoryInfo)){

      $data['categories'] = Category::where('parent','!=', 0)->where('status', 1)->get();
      $data['brands'] = Brand::where('status', '!=' ,5)->where('category_id', $categoryId)->get();
      $data['categoryInfo'] = $categoryInfo;

      return view('brand.index', $data);  
  }
  else{
    return $this->index();
}

}
}

panel/resources/views/item-type/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Item Type
      <small>Version 2.0</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">type</li>
    </ol>
  </section>
  <section class="content-header" >
   @if(Session::has('info_message'))
   <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Warning! </strong> {{ Session::get('info_message') }}.
  </div>
  @endif

  @if(Session::has('success_message'))

  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Success! </strong> {{ Session::get('success_message') }}.
  </div>
  @endif
</section>
<section class="content">
  <div class="row">
 
<div class="col-md-6">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Add new item</h3>

      <hr>
    </div>

    <div class="box-body table-responsive padding">
      <form action="{{route('item-type.update', $itemInfo->id)}}" method="post">
        <input type="hidden" name="_method" value="PATCH" />
        {{csrf_field()}}
        <div class="form-group">
          <label for="area">Title :</label>
          <input type="text" class="form-control" name="title" value="{{$itemInfo->title}}">
          @if($errors->has('title'))
          <span class="text-danger">required field</span>
          @endif
        </div>
        <div class="form-group">
         <label for="category">Category :</label>
         <select class="form-control" name="category">
          <option value="">--select one--</option>
          @if(!empty($categories))
          @foreach($categories as $key => $category)
          <option value="{{ $category->id }}" {{ $category->id == $itemInfo->category_id ? 'selected' : ''  }}>{{ $category->name }}</option>
          @endforeach
          @endif
        </select>
        @if($errors->has('category'))
        <span class="text-danger">required field</span>
        @endif
      </div>
         <div class="form-group">
       <label for="status">Status :</label>
       <select class="form-control" name="status">
        <option value="1" {{ $itemInfo->status == 1 ? 'selected' : '' }}>Active</option>
        <option value="0" {{ $itemInfo->status == 0 ? 'selected' : '' }}>Inactive</option>
       </select>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>
</div>
</div>
</section>
</div>
@push('bottom-script')
<script>
  $(function () {
    $('#itemTypeTable').DataTable()

})
</script>
<script type="text/javascript">
  $('body').on('change', '#productCategory', function() {
    var catId = $(this).val();
   var siteUrl = $('#siteUrl').val();
    if(catId == 'all'){
      window.location.href = '{{url("/brand")}}';
    }
    else{
      window.location.href = '{{url("/brand")}}/'+catId;
    }


  });
</script>
@endpush
@endsection

panel/resources/views/item-type/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Item Type
      <small>Version 2.0</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{url('/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">type</li>
    </ol>
  </section>
  <section class="content-header" >
   @if(Session::has('info_message'))
   <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Warning! </strong> {{ Session::get('info_message') }}.
  </div>
  @endif

  @if(Session::has('success_message'))

  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Success! </strong> {{ Session::get('success_message') }}.
  </div>
  @endif
</section>
<section class="content">
  <div class="row">
    <div class="col-md-7">
      <div class="box">
        <div class="box-header">
          <div class="row">
            <div class="col-md-4">
             <form>
               <div class="form-group">
                <label>Category : </label>
                 <select class="form-control" name="status" id="productCategory">
                   <option value="all">All</option>
                   
                   @if(!empty($categories))
                   @foreach($categories as $key => $category)
                   <option value="{{ $category->id }}" @if(isset($categoryInfo)) {{$categoryInfo->id == $category->id ? 'selected' : ''}} @endif >{{ $category->name }}</option>
                   @endforeach
                   @endif
                 </select>
               </div>
             </form>
           </div>
           <div class="col-md-8">
            <div class="pull-right">
             <a href="{{route('category.create')}}" class="btn btn-info">Add new</a>
           </div>

         </div>
       </div>


     </div>

     <div class="box-body table-responsive">
      <table class="table table-hover" id="itemTypeTable">
        <thead>
          <tr>
            <th>SL</th>
            <th>category</th>
            <th>Title</th>

            <th>Status</th>
            
            <th><span  class="pull-right"> Action</span>

            </th>
          </tr>
        </thead>
        <tbody>
          @if(!empty($itemTypes) && (count($itemTypes)>0))
          @foreach($itemTypes as $key => $item)
          <tr>
            <td>{{$key+1}}</td>
            <td>
             <a href="{{url('/brand/'.$item->category_id)}}">{{$item->getCategory->name}}</a> 
            </td>
            <td>
              <a href="javascript:void(0)">{{$item->title}}</a> 
            </td>

            <td>
              @if($item->status == 1)
              <span class="label label-success">Approved</span>
              @else
              <span class="label label-warning">Pending</span>
              @endif
            </td>
            
            <td><span  class="pull-right">
           
           <a href="{{route('item-type.edit', $item->id)}}" class="btn btn-xs btn-info">edit</a> 
           <a href="{{url('item-type/delete/'.$item->id)}}" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-xs btn-danger">delete</a>
         </span>
       </td>
     </tr>
     @endforeach
     @endif
   </tbody>
 </table>
</div>

</div>

</div>
<div class="col-md-5">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">Add new item</h3>

      <hr>
    </div>

    <div class="box-body table-responsive padding">
      <form action="{{route('item-type.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group">
          <label for="area">Title :</label>
          <input type="text" class="form-control" name="title" value="{{old('title')}}">
          @if($errors->has('title'))
          <span class="text-danger">required field</span>
          @endif
        </div>
        <div class="form-group">
         <label for="category">Category :</label>
         <select class="form-control" name="category">
          <option value="">--select one--</option>
          @if(!empty($categories))
          @foreach($categories as $key => $category)
          <option value="{{ $category->id }}">{{ $category->name }}</option>
          @endforeach
          @endif
        </select>
        @if($errors->has('category'))
        <span class="text-danger">required field</span>
        @endif
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</div>
</div>
</div>
</section>
</div>
@push('bottom-script')
<script>
  $(function () {
    $('#itemTypeTable').DataTable()

})
</script>
<script type="text/javascript">
  $('body').on('change', '#productCategory', function() {
    var catId = $(this).val();
   var siteUrl = $('#siteUrl').val();
    if(catId == 'all'){
      window.location.href = '{{url("/brand")}}';
    }
    else{
      window.location.href = '{{url("/brand")}}/'+catId;
    }


  });
</script>
@endpush
@endsection